# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spectral_summing}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Taylor"]
  s.date = %q{2011-06-30}
  s.description = %q{This is not quite built to the level I expect it will someday achieve, so please let me know if you have a suggestion.  The current interface for options requires you to change the source code.  I'll work on that, long-term, but it works right now.  CLI is given if you call the program without any arguments or the wrong number of arguments.}
  s.email = %q{ryanmt@byu.net}
  s.executables = ["spectral_summing.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/spectral_summing.rb",
    "lib/spectral_summing.rb",
    "ms-spectral_summing.gemspec",
    "spec/spec_helper.rb",
    "spec/spectral_summing_spec.rb",
    "spec/tfiles/test.mzXML",
    "spectral_summing.gemspec",
    "testing.mgf"
  ]
  s.homepage = %q{http://github.com/ryanmt/spectral_summing}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{This is a gem that should enable combination of MS/MS spectra into a combined spectrum representative of the total of all of those scans.  Currently, this can be output as an MGF file.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ms-msrun>, [">= 0"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<ms-msrun>, [">= 0"])
      s.add_dependency(%q<bacon>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<ms-msrun>, [">= 0"])
    s.add_dependency(%q<bacon>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

